# Generated by Django 6.0.4 on 2026-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_alter_order_total_amount_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
