# Generated by Django 6.0.4 on 2026-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_receipt_cash_received_receipt_change_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
