# Generated by Django 6.0.4 on 2026-05-31 15:19

import django.db.models.deletion
from django.db import migrations, models


def link_sale_items_to_inventory(apps, schema_editor):
    SaleItem = apps.get_model('cashier', 'SaleItem')
    InventoryItem = apps.get_model('inventory', 'InventoryItem')

    inventory_by_name = {
        item.item_name: item
        for item in InventoryItem.objects.all()
    }

    for sale_item in SaleItem.objects.filter(inventory_item__isnull=True):
        inventory_item = inventory_by_name.get(sale_item.item_name)
        if inventory_item:
            sale_item.inventory_item_id = inventory_item.id
            sale_item.save(update_fields=['inventory_item'])


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_sale_is_voided'),
        ('inventory', '0003_category_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='item',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.inventoryitem'),
        ),
        migrations.RunPython(link_sale_items_to_inventory, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionItem',
        ),
    ]
