# Generated by Django 6.0.4 on 2026-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Drinks', 'Drinks'), ('Snacks', 'Snacks'), ('Noodles', 'Noodles'), ('Dish', 'Dish'), ('Others', 'Others')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('minimum_stock_level', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20)),
            ],
        ),
    ]
