# Generated by Django 6.0.4 on 2026-05-21 15:05

from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    InventoryItem = apps.get_model('inventory', 'InventoryItem')

    category_names = ['Drinks', 'Snacks', 'Noodles', 'Dish', 'Others']
    category_names.extend(
        InventoryItem.objects.exclude(category='').values_list('category', flat=True).distinct()
    )

    for category_name in category_names:
        clean_name = category_name.strip()
        if clean_name:
            Category.objects.get_or_create(name=clean_name)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_restockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
